# Generated by Django 4.0.1 on 2022-01-18 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='codigo_curso',
            new_name='cod_curso',
        ),
    ]
